### ISSUE TITLE
Searching for "continuous effect" doesn't produce any output

### ISSUE THREAD

**Issue by jgabrielygalan** [elainecao93/ruleslawyer#6]
I have the ruleslawyer in my server and searching for {{continuous effect}} yields no output whatsoever.

**Comment by elainecao93** [comment]
Hey, thanks for letting me know! I have noticed that there have been some issues with output since changing over to discord embeds. I think it has something to do with sending results that are too long and get rejected, but I haven't had a chance to look more closely at them. Hopefully I can work on this next week.

Either way, I have added this to the list of queries that don't work. I appreciate you reaching out!

**Comment by elainecao93** [comment]
At some point I fixed this and forgot to close the issue. Thanks for pointing it out!
